import CelularImage from '../../assets/celulares image.png'

export const dbTech = [
  {
    id: 0,
    img: `${CelularImage}`,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    subtitle: 'R$ 30,90',
    antepenultimoTitle: 'R$ 28,90',
    penultimoTitle: 'ou 2x de R$ 49,95 sem juros',
    ultimoTitle: 'Frete grátis',
  },
  {
    id: 1,
    img: `${CelularImage}`,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    subtitle: 'R$ 30,90',
    antepenultimoTitle: 'R$ 28,90',
    penultimoTitle: 'ou 2x de R$ 49,95 sem juros',
    ultimoTitle: 'Frete grátis',
  },
  {
    id: 2,
    img: `${CelularImage}`,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    subtitle: 'R$ 30,90',
    antepenultimoTitle: 'R$ 28,90',
    penultimoTitle: 'ou 2x de R$ 49,95 sem juros',
    ultimoTitle: 'Frete grátis',
  },
  {
    id: 3,
    img: `${CelularImage}`,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    subtitle: 'R$ 30,90',
    antepenultimoTitle: 'R$ 28,90',
    penultimoTitle: 'ou 2x de R$ 49,95 sem juros',
    ultimoTitle: 'Frete grátis',
  },
  {
    id: 4,
    img: `${CelularImage}`,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    subtitle: 'R$ 30,90',
    antepenultimoTitle: 'R$ 28,90',
    penultimoTitle: 'ou 2x de R$ 49,95 sem juros',
    ultimoTitle: 'Frete grátis',
  },
  {
    id: 5,
    img: `${CelularImage}`,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    subtitle: 'R$ 30,90',
    antepenultimoTitle: 'R$ 28,90',
    penultimoTitle: 'ou 2x de R$ 49,95 sem juros',
    ultimoTitle: 'Frete grátis',
  },
  {
    id: 6,
    img: `${CelularImage}`,
    title: 'L',
    subtitle: 'R$ 30,90',
    antepenultimoTitle: 'R$ 28,90',
    penultimoTitle: 'ou 2x de R$ 49,95 sem juros',
    ultimoTitle: 'Frete grátis',
  },
  {
    id: 7,
    img: `${CelularImage}`,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    subtitle: 'R$ 30,90',
    antepenultimoTitle: 'R$ 28,90',
    penultimoTitle: 'ou 2x de R$ 49,95 sem juros',
    ultimoTitle: 'Frete grátis',
  },
]